port: "69"
ip_server: "192.168.0.11"
command:
  sign: "SIGN"
  game_user: "GAME USER"
  game_server: "GAME SERVER"
  MakeMove: "MAKE MOVE"
  TakeChips: "TAKE SHIPS"
  MoveChips: "MOVE CHIPS"
  top: "TOP-SCORES"
  exit: "EXIT"