port: "69"
ip_server: "192.168.0.13"
command:
  sign: "SIGN"
  game_user: "GAME USER"
  game_server: "GAME SERVER"
  start: "START GAME"
  play: "PLAY"
  top: "TOP-SCORES"
  stop: "STOP"
  exit: "EXIT"